language: python

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker pull dhigras/<packagename>-env:latest

install:
  - docker build -t testenv -f Dockerfile.testing .

script:
  - docker run -it testenv "python -m pytest -v"

notifications:
  email: false
  slack:
    rooms:
      # WARNING: do not specify here on public repositories (use Travis encryption instead)
      - dhigras:TPwMxNqVS9FeaTUJNZlMmL6i
    on_failure: change
    on_success: change
    on_pull_requests: false
