FROM dhigras/bathymetry-env:latest

MAINTAINER Dion Häfner <dimh@dhigroup.com>

RUN conda config --add channels conda-forge && \
    conda install -c conda-forge/label/dev rasterio && \
    conda install pytest codecov

WORKDIR /work

COPY private_dependencies private_dependencies
RUN ls -l private_dependencies && \
    for dir in private_dependencies/*/; do \
      echo $dir && \
      pip install -q $dir; \
    done

COPY . bathymetry
RUN ls -l bathymetry
RUN pip install -q ./bathymetry

# set matplotlib backend
ENV MPLBACKEND=Agg

WORKDIR /work/bathymetry
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["coverage run --source=bathymetry,bathyutils -m pytest -v ./bathymetry && codecov"]
